<?php
/**
 * @file
 * Code for the GSB Feature Offsite School Story Content Type feature.
 */

include_once 'gsb_feature_offsite_school_story_ct.features.inc';

/**
 * Implements hook_form_FORM_ID_alter() for event node edit form.
 */
function gsb_feature_offsite_school_story_ct_form_offsite_school_story_node_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id != 'offsite_school_story_node_form') {
    return;
  }

  $language = $form['language']['#value'];

  // Add required field markers. The actual field validation is done in validate callback.
  if (!empty($form['field_program_unlimited'][$language])) {
    $form['field_program_unlimited'][$language]['#title'] .= " " . theme('form_required_marker');
  }

  $form['field_program_unlimited']['#states']['invisible'][':input[name="field_alumni_story[' . $language . ']"]'] = array(
    array('checked' => FALSE),
  );

  // Perform additional validation.
  $form['#validate'][] = 'gsb_feature_offsite_school_story_ct_offsite_school_story_node_form_validate';

}

/**
 * Validate callback for offsite_school_story_node_form.
 *  - Conditionally validate alumni story fields.
 */
function gsb_feature_offsite_school_story_ct_offsite_school_story_node_form_validate($form, &$form_state) {
  $language = $form['language']['#value'];
  $values = $form_state['values'];

  // If offsite_school_story is an alumni story we need to manually validate some required fields.
  if ($values['field_alumni_story'][$language][0]['value'] == TRUE) {

    if (empty($values['field_program_unlimited'][$language][0]['tid'])) {
      $field_label = $form['field_program_unlimited'][$language]['#title'];
      form_set_error('field_program_unlimited]['.$language.'][0][tid', $field_label . ' field is required.');
    }
  }
}
